
services:
  django_app_backend:
    image: thesamihub/django_app_backend:latest

    container_name: "django_app_backend"

    ports:
      - "8000:8000"

    env_file:
      - .env

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

    restart: unless-stopped

  nginx:
    image: nginx:alpine

    container_name: nginx

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    ports:
      - "80:80"

    restart: unless-stopped

    depends_on:
      django_app_backend:
        condition: service_healthy


  django_app_frontend:
    image: thesamihub/django_app_frontend:latest

    container_name: django_app_frontend

    expose:
      - "3000"
    depends_on:
      - django_app_backend

    restart: unless-stopped

