services:
  django_app_backend:
    build:
      context: .

    container_name: "django_app_backend"
    
    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db

    healthchecks:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/ || exit 1"]
      intervals: 30s
      timeout: 5s
      restries: 5
      start_period: 30s

    restart: unless-stopped

  db:
    image: mysql:8

    container_name: "db"

    environment:
      MYSQL_ROOT_PASSWORD: your_password_here
      MYSQL_DATABASE: test_db
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pyour_password_here"]
      intervals: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

    volumes:
      - mysql-data:/var/lib/mysql 

    restart: unless-stopped

  nginx:
    image: nginx:alpine

    container_name: nginx

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    ports:
      - "80:80"

    restart: unless-stopped

    depends_on: 
      django_app_backend:
        condition:service_healthy


  django_app_frontend:
    build:
      context: ./mynotes/

    container_name: django_app_frontend
    
    expose:
      - "3000"
    depends_on:
      - django_app_backend

    restart: unless-stopped


volumes:
  mysql-data:

