server {
    listen 80;

    # Serve React frontend
    location / {
        proxy_pass http://django_app_frontend:80;
        proxy_set_header Host $host;
    }

    # Forward API requests to Django
    location /api/ {
        proxy_pass http://django_app_backend:8000;
        proxy_set_header Host $host;
    }
}
